---
title: "CS5812-FM-SVM"
output: html_document
date: "2024-03-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### CS5812
### Movies dataset - Support Vector Machine Model
*Fiona Kate Morgan*  
Revision: 1.00

#### 0. load the kernlab and class package
```{r}
library(kernlab) # Used for XXX
library(class) # Used for XXX
```

#### 1. data preparation
```{r}
### 1.1 load and inspect the test and train movies data
movies_df <- read.csv("movies_cleaned.csv", stringsAsFactors = T)
str(movies_df)

### 1.2 load the test and train movies data
movies_test <- read.csv("movies_test.csv", stringsAsFactors = T)
movies_train <- read.csv("movies_train.csv", stringsAsFactors = T)
```

#### 2. SVM training
```{r}
### 2.1 define a formula for predicting the diagnosis
###   note: try to use the reformulate function
movies_formula <- reformulate(names(movies_train[, -1]), response = 'Gross_Earnings')

### 2.2 train with SVM (feel free to choose cost and kernel function)
svm_movies_data <- ksvm(movies_formula, data = movies_train, kernel = 'rbfdot', C = 1)
```

#### 3. SVM Results
```{r}
### 3.1 compute the prediction for the test set with the SVM model
svm_movies_pred <- predict(svm_movies_data, test_movies_data[,-1], type= "response")

### 3.2 create a table with actual and predicted values
movies_results <- data.frame(
  actual = movies_test$Gross_Earnings,
  svm = svm_movies_pred,
)

### 3.4 calculate accuracy values from the contingency table
acc_svm_results <- sum(diag(table_svm_results)) / sum(table_svm_results)
acc_svm_results
```